/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRecommendRouteImport } from './routes/api/ai-recommend'
import { Route as ApiPublicRecommendRouteImport } from './routes/api/public/recommend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRecommendRoute = ApiAiRecommendRouteImport.update({
  id: '/api/ai-recommend',
  path: '/api/ai-recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecommendRoute = ApiPublicRecommendRouteImport.update({
  id: '/api/public/recommend',
  path: '/api/public/recommend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-recommend': typeof ApiAiRecommendRoute
  '/api/public/recommend': typeof ApiPublicRecommendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-recommend': typeof ApiAiRecommendRoute
  '/api/public/recommend': typeof ApiPublicRecommendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-recommend': typeof ApiAiRecommendRoute
  '/api/public/recommend': typeof ApiPublicRecommendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai-recommend' | '/api/public/recommend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai-recommend' | '/api/public/recommend'
  id: '__root__' | '/' | '/api/ai-recommend' | '/api/public/recommend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiRecommendRoute: typeof ApiAiRecommendRoute
  ApiPublicRecommendRoute: typeof ApiPublicRecommendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-recommend': {
      id: '/api/ai-recommend'
      path: '/api/ai-recommend'
      fullPath: '/api/ai-recommend'
      preLoaderRoute: typeof ApiAiRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recommend': {
      id: '/api/public/recommend'
      path: '/api/public/recommend'
      fullPath: '/api/public/recommend'
      preLoaderRoute: typeof ApiPublicRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiRecommendRoute: ApiAiRecommendRoute,
  ApiPublicRecommendRoute: ApiPublicRecommendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
